name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'     # trigeruj kad se menja frontend
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      # (Opcionalno) prikaži sadržaj dist radi provere
      - name: List build
        working-directory: frontend
        run: ls -la dist || true

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: vehicle-controller-3f208   # ili izbaci ovo i oslanjaj se na .firebaserc
          channelId: live
          entryPoint: frontend                  # <<< VAŽNO (jer je firebase.json u frontend/)
        # Debug (ako opet pukne, otkomentariši):
        # env:
        #   DEBUG: 'true'
